### ISSUE TITLE
warn(SvPVX(sv)) and croak(SvPVX(sv)) with no format results in errors with  -Werror=format-security

### ISSUE THREAD

**Issue by d-c-d** [jandubois/win32-ole#10]
warn(SvPVX(sv)) and croak(SvPVX(sv)) with no format
results in errors with  -Werror=format-security
  format not a string literal and no format arguments
Pass "%s" format string through to get compile work

( pull request to follow )

**Comment by jandubois** [comment]
Fixed by #11
